### ISSUE TITLE
TypeError: gtfs.tripStopTimes(...).then is not a function

### ISSUE THREAD

**Issue by KasparasGud** [public-transport/gtfs-to-fptf#8]
Installed the library as a CLI running npm install -g https://github.com/public-transport/gtfs-to-fptf.git
since It's not available on npm

Running  gtfs-to-fptf /Users/user/Downloads/gtfs /Users/user/Downloads produces the following error:

TypeError: "stop-" is not a function
    at stops (/Users/user/.npm-packages/lib/node_modules/gtfs-to-fptf/read-gtfs/mapping.js:17:29)
    at Object.stopsStream (/Users/user/.npm-packages/lib/node_modules/gtfs-to-fptf/read-gtfs/db-reader.js:15:15)
    at main (/Users/user/.npm-packages/lib/node_modules/gtfs-to-fptf/generate-fptf/index.js:25:35)
    at convert (/Users/user/.npm-packages/lib/node_modules/gtfs-to-fptf/index.js:25:8)\

I found there was a '+' missing in the mapping.js file

`const dbToData = {
	agency: (agencyId) => 'agency-' + (agencyId || ''),
	stops: (stopId) => 'stop-' **+** (stopId || ''),
	routes: routeId => 'route-' + (routeId || ''),`

But after fixing and running again it produces a new issue I can't seem to figure out:

gtfs.tripStopTimes(gtfsTrip.trip_id).then((stopTimes) => {
                                             ^

TypeError: gtfs.tripStopTimes(...).then is not a function
    at ReadStream.gtfsTrips.on (/Users/user/.npm-packages/lib/node_modules/gtfs-to-fptf/generate-fptf/index.js:38:46)

Edit: I tested the library using gtfs files from Vilnius, Lithuania and New York (MTA New York City Transit)

**Comment by juliuste** [comment]
Thank you for informing us, I will fix this today and publish to npm.

**Comment by juliuste** [comment]
Should be fixed now. Also, I published `gtfs-to-fptf@0.1.0` to npm.

Reopen this issue if it's still crashing (hopefully it won't) 🙂
